name:                compact-hs
version:             0.1.0.0
license:             BSD3
github:              "feb29/compact-hs"
author:              "Kohei Watanabe"
maintainer:          "xbeef29@gmail.com"
copyright:           "2018 Kohei Watanabe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/feb29/compact-hs#readme>

dependencies:
- base   >= 4.7  && < 5
- vector >= 0.12 && < 1

library:
  source-dirs: src

executables:
  compact-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compact-hs

tests:
  compact-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compact-hs

benchmarks:
  compact-hs-benchmark:
    main:                Benchmark.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compact-hs
    - criterion
